version = 0.1

[default.deploy.parameters]
stack_name = "lambda-stack"
resolve_s3 = true
s3_prefix = "lambda-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "CodeBucket=\"cloudfromation-bucket-abdelhak-e-commerce \""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
